[package]
name = "esl"
version = "0.4.2"
authors = ["warlock <internalmike@gmail.com>"]
description = "A library for reading, writing and processing ESM/ESP/ESS files."
readme = "README.md"
documentation = "https://docs.rs/esl/"
keywords = ["esm", "esp", "ess", "mw", "serde"]
categories = ["encoding"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/esl"
edition = "2018"
build = "build.rs"

[dependencies]
enum_derive = "0.1.7"
enum-primitive-derive = "0.2.1"
num-traits = "0.2.12"
macro-attr = "0.2.0"
either = { version = "1.5.3", features = ["serde"] }
bitflags = "1.2.1"
nom = "5.1.2"
encoding = "0.2.33"
once_cell = "1.4.0"
flate2 = "1.0.14"
serde = { version = "1.0.114", features = ["derive"] }
byteorder = "1.3.4"
derivative = "2.1.1"
nameof = "1.2.1"
base64 = "0.12.2"

[build-dependencies]
serde = { version = "1.0.114", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8.13"
bincode = "1.2.1"
