[package]
name = "tes3"
version = "0.13.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
enum_derive = "0.1.7"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.11"
macro-attr = "0.2.0"
