[package]
edition = "2021"
name = "esl"
version = "0.9.0"
#rust-version = "nightly"
authors = ["warlock <internalmike@gmail.com>"]
description = "A library for reading, writing and processing ESM/ESP/ESS files."
readme = "README.md"
documentation = "https://docs.rs/esl/"
keywords = ["esm", "esp", "ess", "mw", "serde"]
categories = ["encoding"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/A1-Triard/esl"

[dependencies]
base64 = "0.13.0"
bitflags = "1.2.1"
byteorder = "1.3.4"
educe = "0.4.13"
either = { version = "1.5.3", features = ["serde"] }
encoding = "0.2.33"
enum-derive-2018 = "2.0.1"
enumn = "0.1.3"
flate2 = "1.0.14"
macro-attr-2018 = "2.1.2"
nameof = "1.2.1"
nom = "7.1.1"
serde = { version = "1.0.114", features = ["derive"] }

[build-dependencies]
serde = { version = "1.0.114", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8.13"
bincode = "1.2.1"

[badges]
maintenance = { status = "actively-developed" }
