[package]
name = "esl"
version = "0.2.0"
authors = ["warlock <internalmike@gmail.com>"]
description = "A library for reading, writing and processing ESM/ESP/ESS files."
readme = "README.md"
documentation = "https://docs.rs/esl/"
keywords = ["esm", "esp", "ess", "mw", "serde"]
categories = ["encoding"]
license = "MIT/Apache-2.0"
repository = "https://github.com/A1-Triard/esl"
edition = "2018"
build = "build.rs"

[dependencies]
enum_derive = "0.1.7"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.11"
macro-attr = "0.2.0"
either = { version = "1.5.3", features = ["serde"] }
bitflags = "1.2.1"
nom = "5.1.0"
encoding = "0.2.33"
debug_panic = "0.1.2"
lazy_static = "1.4.0"
flate2 = "1.0.13"
serde = { version = "1.0.104", features = ["derive"] }
byteorder = "1.3.4"
derivative = "1.0.3"
nameof = "1.2.0"
base64 = "0.11.0"

[build-dependencies]
serde = { version = "1.0.104", features = ["derive"] }

[dev-dependencies]
serde_yaml = "0.8.11"
bincode = "1.2.1"
