[package]
name = "tes3"
version = "0.13.0"
authors = ["Warlock <internalmike@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
enum_derive = "0.1.7"
enum-primitive-derive = "0.1.2"
num-traits = "0.2.11"
macro-attr = "0.2.0"
either = "1.5.3"
bitflags = "1.2.1"
nom = "5.1.0"
encoding = "0.2.33"
debug_panic = "0.1.2"
lazy_static = "1.4.0"
flate2 = "1.0.13"
serde = { version = "1.0.104", features = ["derive"] }

[build-dependencies]
serde = { version = "1.0.104", features = ["derive"] }
