#!/bin/sh

mkdir -p test_data
cd test_data
if [ \! -e "Data Files/Aleanne Armor and Clothes 1+2.esp" ]; then
  wget -O ale-clothing-v1-1c.7z 'http://www.fullrest.ru/files/ale-clothing-v1-1c/files?fid=2379' || exit 1
  7z x ale-clothing-v1-1c.7z || exit 1
fi
if [ \! -e Morrowind.esm ]; then
  echo "Put Morrowind.esm into test_data"
  exit 1
fi
if [ \! -e Tribunal.esm ]; then
  echo "Put Tribunal.esm into test_data"
  exit 1
fi
if [ \! -e Bloodmoon.esm ]; then
  echo "Put Bloodmoon.esm into test_data"
  exit 1
fi
cd ..

test_file="test_data/Data Files/Aleanne Armor and Clothes 1+2"
echo "${test_file}.esp"
rm -rf "${test_file}" "${test_file}.test.esp" "${test_file}.test"
stack exec -- espa -vad "${test_file}.esp" || exit 1
mv "${test_file}" "${test_file}.test"
stack exec -- espa -v "${test_file}.test" || exit 1
cmp "${test_file}.test.esp" "${test_file}.esp" || exit 1

test_file="test_data/Morrowind"
echo "${test_file}.esm"
rm -rf "${test_file}" "${test_file}.test.esm" "${test_file}.test"
stack exec -- espa -vad "${test_file}.esm" || exit 1
mv "${test_file}" "${test_file}.test"
stack exec -- espa -v "${test_file}.test" || exit 1
cmp "${test_file}.test.esm" "${test_file}.esm" || exit 1

test_file="test_data/Tribunal"
echo "${test_file}.esm"
rm -rf "${test_file}" "${test_file}.test.esm" "${test_file}.test"
stack exec -- espa -vad "${test_file}.esm" || exit 1
mv "${test_file}" "${test_file}.test"
stack exec -- espa -v "${test_file}.test" || exit 1
cmp "${test_file}.test.esm" "${test_file}.esm" || exit 1

test_file="test_data/Bloodmoon"
echo "${test_file}.esm"
rm -rf "${test_file}" "${test_file}.test.esm" "${test_file}.test"
stack exec -- espa -vad "${test_file}.esm" || exit 1
mv "${test_file}" "${test_file}.test"
stack exec -- espa -v "${test_file}.test" || exit 1
cmp "${test_file}.test.esm" "${test_file}.esm" || exit 1

echo "All tests passed."
